version: "3.5"

services:
  nuxt:
    build: ./nuxt
    container_name: nuxt_container_2
    restart: always
    ports:
      - "3004:3003"
    # command: bash -c "npm install && npm run dev"
    command: npm run dev
