version: "3.5"

services:
  nuxt:
    build: ./nuxt
    container_name: nuxt_container
    restart: always
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - django0530

networks:
  django0530:
    external:
      name: django0530_network
